version: '3.8'

services:
  tokens-fetcher:
    container_name: tokens-fetcher
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/src:delegated
    ports:
      - "4550:4550"
    env_file:
      - ../.env
    depends_on:
      - db
      - selenium-hub
    environment:
      NODE_ENV: development
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 4550
      DB_HOST: db
      DB_NAME: tokens_fetcher
    networks:
      - default

  db:
    image: mariadb:10.9.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tokens_fetcher
    ports:
      - "3306:3306"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  default:
    driver: bridge
