/* eslint-disable @typescript-eslint/naming-convention */

export interface RugFreeCoinsAllCoins {
    error: string|null,
    message: string,
    payload: Payload,
}

export interface Payload {
    current_page: number,
    data: RugFreeCoinData[]
    firs_page_url: string,
    from: number|null,
    last_page: number,
    last_page_url: string,
    links: [],
    next_page_url: string|null,
    path: string,
    per_page: string,
    prev_page_url: string|null,
    to: number|null,
    total: number,
}

export interface RugFreeCoinData {
    actual_market_cap: number,
    actual_price: number,
    approved_at: string,
    audited_date: string|null,
    avalanche_token: string|null,
    bsc_contract_address: string|null|undefined,
    coingecko: string|null,
    coinmarketcap: string|null,
    created_at: string,
    description: string,
    discord_link: string|null,
    ethereum_contract_address: string|null|undefined,
    id: number,
    is_audited: number,
    is_doxxed: number,
    is_editor_picked: number,
    is_presale: number,
    is_presale_promoted: number,
    is_promoted: number,
    is_today_promoted: number,
    is_trusted: number,
    is_voted: boolean,
    kcc_token: string|null,
    logo_link: string,
    name: string,
    network: string|null,
    other_links: string|null,
    pancake_swap_link: string|null,
    polygon_token: string|null,
    presale_date: string,
    presale_link: string|null,
    reddit_link: string|null,
    release_date: string,
    remarks: string|null,
    report_link: string|null,
    risk_level: string,
    solana_token: string|null,
    status: string,
    symbol: string,
    telegram_link: string|null,
    tron_token: string|null,
    twitter_link: string|null,
    updated_at: string,
    user_id: number,
    vote_count: number,
    website: string,
}
