export enum ContactMethod {
    EMAIL = 'EMAIL',
    TWITTER = 'TWITTER',
    TELEGRAM = 'TELEGRAM',
    ALL = 'ALL',
}

export enum TokenContactStatusType {
    NOT_CONTACTED = 'NOT_CONTACTED',
    RESPONDED = 'RESPONDED',
    QUEUED = 'QUEUED',
    LIMIT_REACHED = 'LIMIT_REACHED',
    NO_CONTACTS = 'NO_CONTACTS',
}

export enum ContactHistoryStatusType {
    DM_NOT_ENABLED = 'DM_NOT_ENABLED',
    ACCOUNT_NOT_EXISTS = 'ACCOUNT_NOT_EXISTS',
    SUSPENDED = 'SUSPENDED',
    SENT = 'SENT',
    SENT_GROUP = 'SENT_GROUP',
    SENT_GROUP_BUT_DELETED = 'SENT_GROUP_BUT_DELETED',
    SENT_DM = 'SENT_DM',
    UNKNOWN = 'UNKNOWN',
    MESSAGES_NOT_ALLOWED = 'MESSAGES_NOT_ALLOWED',
    ANNOUNCEMENTS_CHANNEL = 'ANNOUNCEMENTS_CHANNEL',
    INVALID_LINK = 'INVALID_LINK',
    ACCOUNT_NOT_AUTHORIZED = 'ACCOUNT_NOT_AUTHORIZED',
    ACCOUNT_LIMIT_HIT = 'ACCOUNT_LIMIT_HIT',
    ACCOUNT_TEMP_BANNED = 'ACCOUNT_TEMP_BANNED',
    ACCOUNT_PERM_BANNED = 'ACCOUNT_PERM_BANNED',
}
